; Script generated by the Inno Setup Script Wizard.
; Non-commercial use only
#define MyAppName "RajaSoftware"
#define MyAppVersion "26.1.2"
#define MyAppPublisher "RAJAGP SIA"
#define MyAppURL "https://rajagp.eu/"
#define MyAppExeName "OpenGL.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

; Build output dir (contains OpenGL.exe + all runtime DLLs, including the
; correct VC145 CRT). Keep this folder up to date by rebuilding Release|x64.
#define ReleaseDir "C:\Users\gamer\source\repos\OpenGL-BONI-MVP-\x64\Release"
#define StylesDir  "C:\Users\gamer\source\repos\OpenGL-BONI-MVP-\OpenGL\styles"
; Готовые трассы, которые едут в дистрибутиве. Остальные три каталога данных
; (results, replays, logs) приложение создаёт само при первом запуске —
; поставлять их пустыми незачем, см. OpenGL\src\core\AppPaths.h.
#define TracksDir  "C:\Users\gamer\source\repos\OpenGL-BONI-MVP-\OpenGL\saves\tracks"
; Драйвер USB-моста CP210x (Silicon Labs). Файлы туда кладут руками, в git их
; нет — см. redist\CP210x\README.txt.
#define DriverDir  "C:\Users\gamer\source\repos\OpenGL-BONI-MVP-\redist\CP210x"

[Setup]
AppId={{B43984B4-4158-409B-8B50-EBA8DCC13D40}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=C:\Users\gamer\Desktop\test license.txt
PrivilegesRequired=lowest
OutputDir=C:\Users\gamer\Desktop
OutputBaseFilename=mysetup
SetupIconFile=C:\Users\gamer\Downloads\Logo Full.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
; Драйвер приёмника. По умолчанию включён: на чистом ПК без него приложение не
; видит устройство вообще. Снять галочку имеет смысл, только если драйвер уже
; стоит — переустановка безвредна, но лишний раз спрашивает UAC.
Name: "cp210xdriver"; Description: "Install USB receiver driver (Silicon Labs CP210x)"; GroupDescription: "Drivers:"

[Files]
; --- Executable ---
Source: "{#ReleaseDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; --- ALL runtime DLLs (app deps + full VC145 CRT redistributable) ---
; Wildcard grabs every DLL next to the exe, so the correct CRT set
; (msvcp140 14.51, vcruntime140, vcruntime140_1, etc.) ships automatically.
; This is the fix for the 0xc0000005 crash caused by an old msvcp140.dll.
; Сюда же попадают vcpkg-зависимости: glfw3.dll, GeographicLib и sqlite3.dll
; (движок БД реестра устройств). Требование: перед сборкой инсталлятора выполнить
;   vcpkg install sqlite3:x64-windows
; и пересобрать Release|x64 — тогда sqlite3.dll окажется рядом с exe и попадёт сюда.
Source: "{#ReleaseDir}\*.dll"; DestDir: "{app}"; Flags: ignoreversion
; --- Styles: fonts, icons, images ---
Source: "{#StylesDir}\*"; DestDir: "{app}\styles"; Flags: ignoreversion recursesubdirs createallsubdirs
; --- Mesa3D software/D3D12 OpenGL fallback (used only if the native GPU can't
;     provide OpenGL 3.3 — e.g. clean VMs, RDP, very old GPUs) ---
Source: "{#ReleaseDir}\mesa\*"; DestDir: "{app}\mesa"; Flags: ignoreversion recursesubdirs createallsubdirs
; --- Трассы. Все данные приложения лежат под одним корнем {app}\saves и
;     разложены по смыслу: tracks / results / replays / logs.
;     Файлы пользователя не затираем: onlyifdoesntexist — переустановка поверх
;     не должна стирать трассу, записанную на прошлой гонке. ---
Source: "{#TracksDir}\*"; DestDir: "{app}\saves\tracks"; Flags: onlyifdoesntexist recursesubdirs createallsubdirs skipifsourcedoesntexist uninsneveruninstall
; --- VC++ x64 redistributable (backstop: installs CRT/UCRT system-wide if missing) ---
Source: "C:\Users\gamer\source\repos\OpenGL-BONI-MVP-\redist\vc_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
; --- Драйвер USB-моста CP210x (Silicon Labs) ---
; Приёмник SX1280 сидит на CP2102. Без драйвера Windows не создаёт COM-порт, а
; приложение перебирает только порты класса Ports — то есть на чистом ПК не
; видит приёмник ВООБЩЕ. Это единственная внешняя зависимость, которую нельзя
; закрыть со стороны приложения, поэтому она едет в дистрибутиве.
; Содержимое папки задаётся вручную, см. redist\CP210x\README.txt: либо
; фирменный CP210xVCPInstaller_x64.exe, либо INF-пакет. Если папки нет —
; шаг установки просто не выполнится (см. [Code]).
Source: "{#DriverDir}\*"; DestDir: "{tmp}\CP210x"; Flags: deleteafterinstall recursesubdirs createallsubdirs skipifsourcedoesntexist

[Dirs]
; Каталоги данных. Приложение создаёт их и само (AppPaths::prepare), но здесь
; они объявлены явно ради прав на запись: под ними лежит всё, что пишется по
; ходу гонки, и обычный пользователь обязан иметь туда доступ.
Name: "{app}\saves";         Permissions: users-modify
Name: "{app}\saves\tracks";  Permissions: users-modify
Name: "{app}\saves\results"; Permissions: users-modify
Name: "{app}\saves\replays"; Permissions: users-modify
Name: "{app}\saves\logs";    Permissions: users-modify

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
; WorkingDir={app} so relative paths (styles\, saves\) resolve from shortcuts
Name: "{group}\{#MyAppName}";                        Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}";   Filename: "{#MyAppURL}"
Name: "{autodesktop}\{#MyAppName}";                  Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
; ВНИМАНИЕ на flags: shellexec. Сам установщик идёт от текущего пользователя
; (PrivilegesRequired=lowest — иначе приложению некуда писать devices.db, логи и
; трассы, они лежат рядом с exe). А vc_redist и установка драйвера требуют
; администратора: их манифест — requireAdministrator. Запуск через CreateProcess,
; то есть [Run] без shellexec, на такой манифест падает с ERROR_ELEVATION_REQUIRED
; и шаг молча не выполняется. ShellExecute поднимает UAC — по одному запросу на шаг
; и только тогда, когда шаг вообще нужен.

; VC++ runtime — только если его нет, чтобы не дёргать UAC на ровном месте.
Filename: "{tmp}\vc_redist.x64.exe"; Parameters: "/install /quiet /norestart"; StatusMsg: "Установка Microsoft Visual C++ Runtime..."; Check: VCRedistNeeded; Flags: shellexec waituntilterminated

; Драйвер CP210x, вариант 1 — фирменный установщик Silicon Labs.
Filename: "{tmp}\CP210x\CP210xVCPInstaller_x64.exe"; Parameters: "/Q"; StatusMsg: "Установка драйвера USB-приёмника (CP210x)..."; Tasks: cp210xdriver; Check: HaveVendorDriverExe; Flags: shellexec waituntilterminated
; Вариант 2 — универсальный INF-пакет через хранилище драйверов Windows.
; /install доставляет драйвер уже подключённым устройствам, /subdirs забирает
; арх-подкаталоги пакета.
Filename: "{sys}\pnputil.exe"; Parameters: "/add-driver ""{tmp}\CP210x\*.inf"" /subdirs /install"; StatusMsg: "Установка драйвера USB-приёмника (CP210x)..."; Tasks: cp210xdriver; Check: UseInfDriver; Flags: shellexec waituntilterminated

Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function VCRedistNeeded(): Boolean;
var
  Installed: Cardinal;
begin
  // VC++ 2015-2022 x64 runtime registers here (64-bit view)
  Result := True;
  if RegQueryDWordValue(HKLM64, 'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64', 'Installed', Installed) then
    if Installed = 1 then
      Result := False;
end;

// --- Драйвер CP210x -------------------------------------------------------
// Форма поставки драйвера выбирается по тому, что реально лежит в пакете, а не
// задаётся заранее: так один и тот же installer.iss собирается и с фирменным
// установщиком Silicon Labs, и с универсальным INF-пакетом, и вообще без
// драйвера (тогда шаг просто пропускается, а не ломает сборку).

function HaveVendorDriverExe(): Boolean;
begin
  Result := FileExists(ExpandConstant('{tmp}\CP210x\CP210xVCPInstaller_x64.exe'));
end;

function UseInfDriver(): Boolean;
var
  Found: TFindRec;
begin
  Result := False;
  // Фирменный установщик приоритетнее: он сам разбирается с разрядностью и с
  // уже стоящей старой версией.
  if HaveVendorDriverExe() then
    Exit;

  if FindFirst(ExpandConstant('{tmp}\CP210x\*.inf'), Found) then
  begin
    Result := True;
    FindClose(Found);
  end;
end;
